package org.bob.learn.dao.model;

import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blacklist
 */
public class Blacklist {
    /**
     * Database Column Remarks:
     *   黑名单标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.038+08:00", comments="Source field: blacklist.bid")
    private Long bid;

    /**
     * Database Column Remarks:
     *   网关mac
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.mac")
    private String mac;

    /**
     * Database Column Remarks:
     *   网关sn
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.sn")
    private String sn;

    /**
     * Database Column Remarks:
     *   下挂设备mac
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.dmac")
    private String dmac;

    /**
     * Database Column Remarks:
     *   网站host
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.host")
    private String host;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.create_time")
    private LocalDateTime createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.042+08:00", comments="Source field: blacklist.bid")
    public Long getBid() {
        return bid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.bid")
    public void setBid(Long bid) {
        this.bid = bid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.mac")
    public String getMac() {
        return mac;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.mac")
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.sn")
    public String getSn() {
        return sn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.sn")
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.dmac")
    public String getDmac() {
        return dmac;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.dmac")
    public void setDmac(String dmac) {
        this.dmac = dmac == null ? null : dmac.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.host")
    public String getHost() {
        return host;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.043+08:00", comments="Source field: blacklist.host")
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.044+08:00", comments="Source field: blacklist.create_time")
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:34:47.044+08:00", comments="Source field: blacklist.create_time")
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}