package org.bob.learn.dao.model;

import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table risk_record
 */
public class RiskRecord {
    /**
     * Database Column Remarks:
     *   风险网站访问记录标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.065+08:00", comments="Source field: risk_record.rid")
    private Long rid;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.create_time")
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   网关mac
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.mac")
    private String mac;

    /**
     * Database Column Remarks:
     *   网关sn
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.sn")
    private String sn;

    /**
     * Database Column Remarks:
     *   设备mac
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.dmac")
    private String dmac;

    /**
     * Database Column Remarks:
     *   设备名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.dname")
    private String dname;

    /**
     * Database Column Remarks:
     *   网站host
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.host")
    private String host;

    /**
     * Database Column Remarks:
     *   处置结果，0：已告警，1、已拦截，2，已放行
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.deal_state")
    private String dealState;

    /**
     * Database Column Remarks:
     *   阅读状态，0：未查看，1：已查看
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.read_state")
    private String readState;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.update_time")
    private LocalDateTime updateTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.rid")
    public Long getRid() {
        return rid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.rid")
    public void setRid(Long rid) {
        this.rid = rid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.create_time")
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.create_time")
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.mac")
    public String getMac() {
        return mac;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.mac")
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.sn")
    public String getSn() {
        return sn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.069+08:00", comments="Source field: risk_record.sn")
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.dmac")
    public String getDmac() {
        return dmac;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.dmac")
    public void setDmac(String dmac) {
        this.dmac = dmac == null ? null : dmac.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.dname")
    public String getDname() {
        return dname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.dname")
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.host")
    public String getHost() {
        return host;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.host")
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.deal_state")
    public String getDealState() {
        return dealState;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.deal_state")
    public void setDealState(String dealState) {
        this.dealState = dealState == null ? null : dealState.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.read_state")
    public String getReadState() {
        return readState;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.read_state")
    public void setReadState(String readState) {
        this.readState = readState == null ? null : readState.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.07+08:00", comments="Source field: risk_record.update_time")
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-10-15T14:50:06.071+08:00", comments="Source field: risk_record.update_time")
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}